version: '3.1'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASS}
  billing-be:
    build:
      context: .
    ports:
      - 4000:3000
    environment:
      PORT: 3000
      DATABASE_URI: mongodb://mongodb-user:mongodb-pass@mongo:27017